CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115191833_adds_categories_table') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(20) NOT NULL,
        "ParentId" integer,
        "InsertDate" timestamp with time zone,
        "UpdatenDate" timestamp with time zone,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categories_Categories_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Categories" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115191833_adds_categories_table') THEN
    CREATE UNIQUE INDEX "IX_Categories_Name" ON "Categories" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115191833_adds_categories_table') THEN
    CREATE INDEX "IX_Categories_ParentId" ON "Categories" ("ParentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115191833_adds_categories_table') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20241115191833_adds_categories_table', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115193457_adds_periods_table') THEN
    CREATE TABLE "Periods" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Start" date NOT NULL,
        "End" date NOT NULL,
        "Description" character(5) NOT NULL,
        "InsertDate" timestamp with time zone,
        "UpdatenDate" timestamp with time zone,
        CONSTRAINT "PK_Periods" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115193457_adds_periods_table') THEN
    CREATE UNIQUE INDEX "IX_Periods_Description" ON "Periods" ("Description");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115193457_adds_periods_table') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20241115193457_adds_periods_table', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115194138_adds_institutions_table') THEN
    CREATE TABLE "Institutions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(20) NOT NULL,
        "InitialBalance" numeric NOT NULL,
        "Balance" numeric NOT NULL,
        "InsertDate" timestamp with time zone,
        "UpdatenDate" timestamp with time zone,
        CONSTRAINT "PK_Institutions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115194138_adds_institutions_table') THEN
    CREATE UNIQUE INDEX "IX_Institutions_Name" ON "Institutions" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115194138_adds_institutions_table') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20241115194138_adds_institutions_table', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115195343_adds_movimentations_table') THEN
    CREATE TABLE "Movimentations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Date" date NOT NULL,
        "Description" character varying(30) NOT NULL,
        "Value" numeric NOT NULL,
        "CategoryId" integer NOT NULL,
        "PeriodId" integer NOT NULL,
        "InstitutionId" integer NOT NULL,
        "InsertDate" timestamp with time zone,
        "UpdatenDate" timestamp with time zone,
        CONSTRAINT "PK_Movimentations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Movimentations_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Movimentations_Institutions_InstitutionId" FOREIGN KEY ("InstitutionId") REFERENCES "Institutions" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Movimentations_Periods_PeriodId" FOREIGN KEY ("PeriodId") REFERENCES "Periods" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115195343_adds_movimentations_table') THEN
    CREATE INDEX "IX_Movimentations_CategoryId" ON "Movimentations" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115195343_adds_movimentations_table') THEN
    CREATE INDEX "IX_Movimentations_InstitutionId" ON "Movimentations" ("InstitutionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115195343_adds_movimentations_table') THEN
    CREATE INDEX "IX_Movimentations_PeriodId" ON "Movimentations" ("PeriodId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115195343_adds_movimentations_table') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20241115195343_adds_movimentations_table', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115195511_edits_delete_behavior_categories_table') THEN
    ALTER TABLE "Categories" DROP CONSTRAINT "FK_Categories_Categories_ParentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115195511_edits_delete_behavior_categories_table') THEN
    ALTER TABLE "Categories" ADD CONSTRAINT "FK_Categories_Categories_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20241115195511_edits_delete_behavior_categories_table') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20241115195511_edits_delete_behavior_categories_table', '8.0.11');
    END IF;
END $EF$;
COMMIT;

